<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>Sassafras - ZF2 Bootstrap SASS Quick Start</title>
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/js/vendor/bootstrap/docs/assets/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/js/vendor/bootstrap/docs/assets/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/js/vendor/bootstrap/docs/assets/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/js/vendor/bootstrap/docs/assets/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/img/favicon.ico">
<link href="/css/style.css" rel="stylesheet">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <a class="navbar-brand" href="#">Sassafras - ZF2 Bootstrap SASS Quick Start</a> 
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>
    </div>
  </div>
</div>

<?php echo $this->content ?>

<footer>
  <div class="container">
    <p>&copy; Sassafras 2014 - by Tom Shaw</p>
  </div>
</footer>

<script src="/js/vendor/jquery/dist/jquery.min.js"></script> 
<script src="/js/vendor/bootstrap-sass/dist/js/bootstrap.min.js"></script>
<script src="/js/vendor/underscore/underscore.js"></script>
<script src="/js/script.js"></script>
<script src="http://localhost:35729/livereload.js"></script>

</body>
</html>
