<div class="jumbotron">
  <div class="container">
    <h1>Sassafras!</h1>
    <p>Sassafras is a genus of three extant and one extinct species of deciduous trees in the family Lauraceae, native to eastern North America and eastern Asia.</p>
    <p><a href="http://en.wikipedia.org/wiki/Sassafras" class="btn btn-primary btn-lg" target="_blank">Learn more &raquo;</a></p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Sassafras albidum.</h2>
      <p>(Nuttall) Nees - sassafras, white sassafras, red sassafras or silky sassafras, eastern North America, from southernmost Ontario, Canada through the eastern United States, south to central Florida, and west to southern Iowa and East Texas.</p>
      <p><a class="btn btn-default" href="http://en.wikipedia.org/wiki/Sassafras_albidum" target="_blank">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Sassafras tzumu.</h2>
      <p>(Hemsl.) Hemsl. - Chinese sassafras or Tzumu, central and southwestern China, it differs from S. albidum in the leaves being more frequently three-lobed, the lobes having a tapered acuminate apex (not rounded to weakly acute).</p>
      <p><a class="btn btn-default" href="http://en.wikipedia.org/wiki/Sassafras_hesperia" target="_blank">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Sassafras randaiense.</h2>
      <p>(Hayata) Rehd. - Taiwanese sassafras, Taiwan, is treated by some botanists in a distinct genus as Yushunia randaiensis (Hayata) Kamikoti, though this is not supported by recent genetic evidence, which shows Sassafras to be monophyletic</p>
      <p><a class="btn btn-default" href="http://en.wikipedia.org/wiki/Sassafras_randaiense" target="_blank">View details &raquo;</a></p>
    </div>
  </div>
</div>